### ISSUE TITLE
error downloading data from shiny app

### ISSUE THREAD

**Issue by jpvanek** [TabakM/CameraTrapDetectoR#3]
```
> runShiny("deploy")
Loading required package: shiny

Listening on http://127.0.0.1:3486
trying URL 'https://www.dropbox.com/s/r1pazpf8db2o003/fasterrcnn_5classes.pt?raw=1'
Warning in utils::download.file(url, path, mode = "wb") :
  cannot open URL 'https://www.dropbox.com/s/r1pazpf8db2o003/fasterrcnn_5classes.pt?raw=1': HTTP status was '404 Not Found'
Warning: Error in utils::download.file: cannot open URL 'https://www.dropbox.com/s/r1pazpf8db2o003/fasterrcnn_5classes.pt?raw=1'
  2: shiny::runApp
  1: runShiny

```
Got the package installed and running (didn't work until I upgraded from R v 3.6 to v4), got the shiny app to run, then hit this snag. Typo perhaps?

**Comment by fjoyce** [comment]
Issue seems to be specific to the file path for the general model.

I don't get the same 404 error when I tried using family for model_type

**Comment by fjoyce** [comment]
I ran it on a smaller directory (43 photos) and it took a while (somewhere between 10 & 20 min?)

**Comment by TabakM** [comment]
Thank you for reporting.
I updated the general model URL. Please try again if you get a chance. On timing, it shouldn't take that long, especially with your RAM, John. So I'm not sure what's going on there. 
Did either of you try to run without installing Microsoft Visual C++?

**Comment by mikeyEcology** [comment]
@jpvanek These are the warnings that I cannot suppress that I'm referring to when the output says "two warnings will appear". They are not a problem. You should have a progress bar indicating that things are working, though. If you specified `make_plots=TRUE`, you can also look at those while it's running. 

> [W TensorImpl.h:1156] Warning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (function operator ())
> [W faster_rcnn.py:95] Warning: RCNN always returns a (Losses, Detections) tuple in scripting (function )

**Comment by jpvanek** [comment]
Thanks for the update. I did install MV C++ before installing. The model is still running, will update when it completes.

**Comment by rsmiller74** [comment]
John thanks for doing some evaluation.

Are you pulling the images across a network?  It takes from .75 to 3 seconds per photo when I run it but I am running it on the same drive that contains photos.

You might play around with the score_threshold.  Take a look at the bounding box output file and see if it found those animals but the score was too low to include.

Also be aware that we will be doing some additional model training within the next few weeks.

**Comment by jpvanek** [comment]
Hmm, no I don't think so. I have the folder in C: and R installed on C:. I'll keep playing around with it. Defintely seems user friendly and easy to run/view results.

**Comment by TabakM** [comment]
@jpvanek I wonder if running the model through the Shiny app is slowing it down. You could try running it in the console. After specifying all of your parameters in the Shiny App, you can copy the code at the top of the shiny window. Then instead of running the model through the shiny app, paste this code into the console and try that. More details at `?deploy_model`

Regarding the progress par, that will only appear if you run directly in the console (instead of through the Shiny App).

**Comment by mikeyEcology** [comment]
I'm closing this issue as the downloading problem has been solved. @jpvanek if you have further questions about time to deployment, please open a new issue.
